"""Chromium setup shared by all commands: launch flags, fonts, page options.

The settings make Chromium output stable and comparable with swb. The
reasons for each one are in docs/testing.md ("Chromium settings").
"""

import logging
import os
import tempfile
from collections.abc import AsyncIterator, Awaitable, Callable
from contextlib import asynccontextmanager
from html import escape
from pathlib import Path

from playwright.async_api import (
    Browser,
    BrowserContext,
    Page,
    Playwright,
    async_playwright,
)

from swbtools import paths
from swbtools.boxes import COLLECT_JS, BoxDump, from_page_data
from swbtools.pixels import write_png_unless_close

log = logging.getLogger(__name__)

PAGE_VIEWPORT = (1280, 800)
"""Viewport for page fixtures, in CSS px."""

LAYOUT_VIEWPORT = (800, 600)
"""Viewport for layout tests, in CSS px."""

CHROMIUM_ARGS = [
    # Linear (unhinted) glyph advances also for fallback fonts. Without it,
    # the headless shell hints the advances of fallback glyphs to whole
    # pixels.
    "--font-render-hinting=none",
    # Grayscale anti-aliasing and plain sRGB output, as swb renders.
    "--disable-lcd-text",
    "--force-color-profile=srgb",
]

# Rendering settings added to the bundled fonts.conf. fontconfig's default
# is full hinting, which makes Chromium round glyph advances to whole pixels.
# swb uses unhinted outlines and unrounded advances.
_RENDER_SETTINGS = """\
  <match target="font">
    <edit name="antialias" mode="assign"><bool>true</bool></edit>
    <edit name="hinting" mode="assign"><bool>false</bool></edit>
    <edit name="hintstyle" mode="assign"><const>hintnone</const></edit>
    <edit name="rgba" mode="assign"><const>none</const></edit>
    <edit name="embeddedbitmap" mode="assign"><bool>false</bool></edit>
  </match>
"""


def write_fontconfig() -> Path:
    """Writes `out/fontconfig/fonts.conf`: the bundled `fonts.conf` plus
    rendering settings. Returns its path."""
    bundled = paths.fonts_conf()
    if not bundled.is_file():
        raise FileNotFoundError(f"{bundled} does not exist; use --system-fonts")
    wrapper = paths.out_dir() / "fontconfig" / "fonts.conf"
    wrapper.parent.mkdir(parents=True, exist_ok=True)
    wrapper.write_text(
        '<?xml version="1.0"?>\n'
        '<!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">\n'
        "<!-- Generated by swbtools (tools/swbtools/browser.py). Do not edit. -->\n"
        "<fontconfig>\n"
        f"  <include>{escape(str(bundled))}</include>\n"
        f"{_RENDER_SETTINGS}"
        "</fontconfig>\n",
        encoding="utf-8",
    )
    return wrapper


def browser_env(system_fonts: bool) -> dict[str, str]:
    """Returns the environment for Chromium."""
    env = dict(os.environ)
    if not system_fonts:
        env["FONTCONFIG_FILE"] = str(write_fontconfig())
    return env


async def launch(playwright: Playwright, system_fonts: bool = False) -> Browser:
    """Launches headless Chromium with the test settings."""
    browser = await playwright.chromium.launch(
        args=CHROMIUM_ARGS, env=browser_env(system_fonts), headless=True
    )
    log.info("Chromium %s", browser.version)
    return browser


async def new_context(browser: Browser, viewport: tuple[int, int]) -> BrowserContext:
    """Creates a browser context: JavaScript disabled, device scale factor 1,
    and the same media features as swb."""
    width, height = viewport
    return await browser.new_context(
        viewport={"width": width, "height": height},
        device_scale_factor=1,
        java_script_enabled=False,
        locale="en-US",
        color_scheme="light",
        reduced_motion="no-preference",
        service_workers="block",
    )


@asynccontextmanager
async def session(
    viewport: tuple[int, int], system_fonts: bool = False
) -> AsyncIterator[tuple[Browser, BrowserContext, Page]]:
    """Starts Chromium with the test settings and yields the browser, a
    context with `viewport` and a new page. Closes Chromium on exit, also
    when the body fails."""
    async with async_playwright() as playwright:
        chromium = await launch(playwright, system_fonts)
        try:
            context = await new_context(chromium, viewport)
            yield chromium, context, await context.new_page()
        finally:
            await chromium.close()


async def in_chromium[T](run: Callable[[Page, Path], Awaitable[T]]) -> T:
    """Calls `run` with a Chromium page (the layout test settings) and a
    temporary directory for the pages."""
    async with session(LAYOUT_VIEWPORT) as (_, _, page):
        with tempfile.TemporaryDirectory(prefix="swb-measure-") as directory:
            return await run(page, Path(directory))


async def load_html(page: Page, path: Path, html: str) -> None:
    """Writes `html` to `path` and loads that file in `page`."""
    path.write_text(html, encoding="utf-8")
    await page.goto(path.as_uri(), wait_until="load")


async def scroll_through(page: Page, pause_ms: int = 250) -> None:
    """Scrolls down the whole page in steps, then back to the top, so that
    lazy-loaded images load."""
    step = int(page.viewport_size["height"] * 0.8) if page.viewport_size else 600
    y = 0
    while True:
        height = await page.evaluate("document.documentElement.scrollHeight")
        if y >= height:
            break
        await page.evaluate(f"window.scrollTo(0, {y})")
        await page.wait_for_timeout(pause_ms)
        y += step
    await page.evaluate("window.scrollTo(0, 0)")


# A constructed stylesheet, so that no element is added to the document.
_STOP_ANIMATIONS_JS = """
() => {
  const sheet = new CSSStyleSheet();
  sheet.replaceSync(
    '*, *::before, *::after { animation: none !important; transition: none !important; }'
  );
  document.adoptedStyleSheets = [...document.adoptedStyleSheets, sheet];
}
"""


async def stop_animations(page: Page) -> None:
    """Turns off CSS animations and transitions, so that every element has
    its base style. Box dumps and screenshots then do not depend on timing.
    swb does not run animations either."""
    await page.evaluate(_STOP_ANIMATIONS_JS)


_WAIT_FOR_FONTS_JS = """
async () => {
  // Layout starts the loads of the fonts that the text uses; a load that
  // starts after the `load` event is not part of it. Force layout, wait,
  // and repeat for loads that the first fonts' text triggers.
  for (let i = 0; i < 3; i++) {
    document.documentElement.offsetHeight;
    await document.fonts.ready;
  }
}
"""


async def wait_for_fonts(page: Page) -> None:
    """Waits until the web fonts that the page uses have loaded (or
    failed), so that measurements do not depend on the timing of the font
    loads."""
    await page.evaluate(_WAIT_FOR_FONTS_JS)


async def collect_boxes(page: Page, url: str) -> BoxDump:
    """Returns the box dump of the page. Call it with the page scrolled to
    the top, so that fixed elements are at their initial position."""
    return from_page_data(url, await page.evaluate(COLLECT_JS))


async def screenshot(page: Page, path: Path) -> None:
    """Saves a PNG of the first viewport. Keeps an existing file that differs
    only by noise (see `write_png_unless_close`)."""
    png = await page.screenshot(animations="disabled", caret="hide")
    write_png_unless_close(path, png)


async def wait_for_network_idle(page: Page, timeout_ms: int = 15000) -> None:
    """Waits until the page makes no requests for 500 ms. Logs a timeout."""
    try:
        await page.wait_for_load_state("networkidle", timeout=timeout_ms)
    except Exception as error:
        log.warning("network did not become idle: %s", error)
