"""`swbtools js-unicode-tables`: Unicode tables for the JavaScript lexer.

Writes `crates/js-text/src/unicode/tables.rs` from the Unicode Character
Database (`ucd.py` downloads the files into `out/ucd/`):

- `ID_START`, `ID_CONTINUE`: the properties ID_Start and ID_Continue
  (ECMA-262 §12.7, UnicodeIDStart and UnicodeIDContinue).
- `SPACE_SEPARATORS`: General_Category Zs, the USP of ECMA-262 §12.2.

The tables are sorted, disjoint ranges of code points.
"""

from pathlib import Path

from swbtools import paths
from swbtools.ucd import has_property, ranges, read_property, ucd_file

VERSION = "17.0.0"
"""The Unicode version of the tables."""

FILES = {
    "DerivedCoreProperties": "ucd/DerivedCoreProperties.txt",
    "DerivedGeneralCategory": "ucd/extracted/DerivedGeneralCategory.txt",
}


def range_table(name: str, doc: str, items: list[tuple[int, int]]) -> list[str]:
    """The Rust source of one range table."""
    lines = [f"/// {doc}", f"pub(super) static {name}: [(u32, u32); {len(items)}] = ["]
    lines += [f"    (0x{a:04X}, 0x{b:04X})," for a, b in items]
    lines += ["];", ""]
    return lines


def generate_tables(core: Path, category: Path) -> str:
    """Returns the Rust source of `tables.rs` from the two UCD files."""
    lines = [
        "//! Unicode data for the JavaScript lexer. Generated by",
        "//! `swbtools js-unicode-tables` (`tools/swbtools/js_unicode_tables.py`) from",
        f"//! the Unicode Character Database {VERSION}",
        f"//! (<https://www.unicode.org/Public/{VERSION}/ucd/>). Do not edit.",
        "",
    ]
    lines += range_table(
        "ID_START",
        "`ID_Start`: `UnicodeIDStart` of ECMA-262 §12.7.",
        ranges(has_property(core, "ID_Start")),
    )
    lines += range_table(
        "ID_CONTINUE",
        "`ID_Continue`: `UnicodeIDContinue` of ECMA-262 §12.7.",
        ranges(has_property(core, "ID_Continue")),
    )
    lines += range_table(
        "SPACE_SEPARATORS",
        "`General_Category` Zs: USP of ECMA-262 §12.2.",
        ranges([gc == "Zs" for gc in read_property(category, "Cn")]),
    )
    return "\n".join(lines).rstrip("\n") + "\n"


def tables_path() -> Path:
    """Returns `crates/js-text/src/unicode/tables.rs`."""
    return paths.repo_root() / "crates" / "js-text" / "src" / "unicode" / "tables.rs"


def write_tables() -> int:
    """Writes `tables.rs`. Returns the exit code."""
    source = generate_tables(
        ucd_file(FILES["DerivedCoreProperties"], VERSION),
        ucd_file(FILES["DerivedGeneralCategory"], VERSION),
    )
    path = tables_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(source, encoding="utf-8")
    print(f"wrote {path.relative_to(paths.repo_root())}")
    return 0
