//! The fragment tree: the output of layout.
//!
//! Every fragment's position is relative to the border-box origin of its
//! parent [`BoxFragment`]. The root fragment is positioned relative to the
//! initial containing block (the page origin). Use [`FragmentTree::walk`]
//! to visit fragments with absolute positions.

use std::sync::Arc;

use swb_dom::NodeId;
use swb_style::{ComputedStyle, PseudoKind};
use swb_text::{FontId, GlyphId};

use crate::geom::{Edges, Point, Rect};

/// The result of laying out a document.
#[derive(Clone, Debug)]
pub struct FragmentTree {
    /// The fragment of the root element, or `None` if the document has no
    /// rendered root.
    pub root: Option<BoxFragment>,
    /// The background of the canvas (propagated from the root or body).
    pub canvas_background: Option<CanvasBackground>,
    /// The size of the scrollable area: the union of the initial containing
    /// block and all content.
    pub scroll_size: crate::geom::Size,
}

/// The background that paints the canvas, and the element it comes from.
/// That element does not paint its background again.
#[derive(Clone, Debug)]
pub struct CanvasBackground {
    /// The root element or the body.
    pub source: NodeId,
    /// The style with the background.
    pub style: Arc<ComputedStyle>,
}

/// A reference to a fragment of either kind.
#[derive(Clone, Copy, Debug)]
pub enum FragmentRef<'a> {
    /// A box fragment.
    Box(&'a BoxFragment),
    /// A text fragment.
    Text(&'a TextFragment),
}

impl FragmentTree {
    /// Calls `visit` for every fragment, the root included, in tree order
    /// (parents before children). The second argument is the absolute
    /// position of the fragment's parent border-box origin.
    pub fn walk<'a>(&'a self, mut visit: impl FnMut(FragmentRef<'a>, Point)) {
        fn walk_box<'a>(
            b: &'a BoxFragment,
            origin: Point,
            visit: &mut impl FnMut(FragmentRef<'a>, Point),
        ) {
            visit(FragmentRef::Box(b), origin);
            let own_origin = origin + b.border_rect.origin();
            for child in b.children.iter() {
                match child {
                    Fragment::Box(cb) => walk_box(cb, own_origin, visit),
                    Fragment::Text(t) => visit(FragmentRef::Text(t), own_origin),
                }
            }
        }
        if let Some(root) = &self.root {
            walk_box(root, Point::default(), &mut visit);
        }
    }

    /// The union of the absolute border boxes of each element's fragments
    /// (pseudo-element boxes excluded).
    pub fn element_boxes(&self) -> std::collections::HashMap<NodeId, Rect> {
        let mut boxes: std::collections::HashMap<NodeId, Rect> = std::collections::HashMap::new();
        self.walk(|f, origin| {
            if let FragmentRef::Box(b) = f
                && let Some(node) = b.node
                && b.pseudo.is_none()
            {
                let rect = b.border_rect.translate(origin);
                boxes
                    .entry(node)
                    .and_modify(|r| *r = r.union(&rect))
                    .or_insert(rect);
            }
        });
        boxes
    }

    /// The absolute border boxes of all fragments generated by `node`, in
    /// tree order. An inline element split across lines has several.
    pub fn border_boxes(&self, node: NodeId) -> Vec<Rect> {
        let mut out = Vec::new();
        self.walk(|f, origin| {
            if let FragmentRef::Box(b) = f
                && b.node == Some(node)
                && b.pseudo.is_none()
            {
                out.push(b.border_rect.translate(origin));
            }
        });
        out
    }
}

/// A fragment.
#[derive(Clone, Debug)]
pub enum Fragment {
    /// A box (block, inline box piece, atomic inline, replaced element).
    Box(BoxFragment),
    /// A run of glyphs on one line.
    Text(TextFragment),
}

/// What a box fragment contains besides its children.
#[derive(Clone, Debug, PartialEq)]
pub enum BoxContent {
    /// Nothing special.
    None,
    /// The image of a replaced element, painted into the content box.
    Image(NodeId),
}

/// The fragment of a box.
#[derive(Clone, Debug)]
pub struct BoxFragment {
    /// The element that generated the box; `None` for anonymous boxes.
    pub node: Option<NodeId>,
    /// The pseudo-element, if the box was generated by one.
    pub pseudo: Option<PseudoKind>,
    /// The box's computed style.
    pub style: Arc<ComputedStyle>,
    /// The border box, relative to the parent fragment's border-box origin.
    pub border_rect: Rect,
    /// Border widths. For inline boxes split across lines, the sides at the
    /// split are zero.
    pub border: Edges,
    /// Padding widths (split sides zero, as for `border`).
    pub padding: Edges,
    /// Replaced content.
    pub content: BoxContent,
    /// Child fragments. Shared, so that copying a fragment is cheap: the
    /// flex item cache returns copies of laid-out subtrees.
    pub children: Arc<Vec<Fragment>>,
    /// The baseline of the first line box in the box (or of the first flex
    /// item that has one), relative to the border-box top, if any.
    pub first_baseline: Option<f32>,
    /// The baseline of the last line box in the box, relative to the
    /// border-box top, if any. The baseline of an inline-block.
    pub last_baseline: Option<f32>,
    /// True if this fragment is part of an inline box (not a block).
    pub is_inline: bool,
}

impl BoxFragment {
    /// The padding box, relative to the parent's border-box origin.
    pub fn padding_rect(&self) -> Rect {
        self.border_rect.inset(&self.border)
    }

    /// The content box, relative to the parent's border-box origin.
    pub fn content_rect(&self) -> Rect {
        self.padding_rect().inset(&self.padding)
    }
}

/// A positioned glyph.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct PositionedGlyph {
    /// The glyph.
    pub id: GlyphId,
    /// Horizontal pen position relative to the text fragment's left edge.
    pub x: f32,
    /// Vertical offset from the baseline (down is positive).
    pub y: f32,
}

/// A run of glyphs in one font on one line.
#[derive(Clone, Debug)]
pub struct TextFragment {
    /// The text node.
    pub node: NodeId,
    /// The style of the text (the parent element's style).
    pub style: Arc<ComputedStyle>,
    /// The text's content area (font ascent to descent), relative to the
    /// parent fragment's border-box origin.
    pub rect: Rect,
    /// The baseline position, relative to `rect.y`.
    pub baseline: f32,
    /// The font.
    pub font: FontId,
    /// The font size in px.
    pub font_size: f32,
    /// The glyphs.
    pub glyphs: Arc<[PositionedGlyph]>,
    /// The text of the run (after white-space processing), for hit
    /// testing, selection and the automation API.
    pub text: Arc<str>,
}
