//! The fragment tree: the output of layout.
//!
//! Every fragment's position is relative to the border-box origin of its
//! parent [`BoxFragment`]. The root fragment is positioned relative to the
//! initial containing block (the page origin). Use [`FragmentTree::walk`]
//! to visit fragments with absolute positions.

use std::sync::Arc;

use swb_dom::NodeId;
use swb_style::{ComputedStyle, PseudoKind};
use swb_text::{FontId, GlyphId};

use crate::geom::{Edges, Point, Rect};

/// The result of laying out a document.
#[derive(Clone, Debug)]
pub struct FragmentTree {
    /// The fragment of the root element, or `None` if the document has no
    /// rendered root.
    pub root: Option<BoxFragment>,
    /// The background of the canvas (propagated from the root or body).
    pub canvas_background: Option<CanvasBackground>,
    /// The size of the scrollable area: the union of the initial containing
    /// block and all content that is not clipped. On an axis where the
    /// viewport's overflow is `hidden` or `clip`, the viewport's size.
    pub scroll_size: crate::geom::Size,
}

/// The background that paints the canvas, and the element it comes from.
/// That element does not paint its background again.
#[derive(Clone, Debug)]
pub struct CanvasBackground {
    /// The root element or the body.
    pub source: NodeId,
    /// The style with the background.
    pub style: Arc<ComputedStyle>,
}

/// A reference to a fragment of either kind.
#[derive(Clone, Copy, Debug)]
pub enum FragmentRef<'a> {
    /// A box fragment.
    Box(&'a BoxFragment),
    /// A text fragment.
    Text(&'a TextFragment),
}

impl FragmentTree {
    /// Calls `visit` for every fragment, the root included, in tree order
    /// (parents before children). The second argument is the absolute
    /// position of the fragment's parent border-box origin.
    pub fn walk<'a>(&'a self, mut visit: impl FnMut(FragmentRef<'a>, Point)) {
        fn walk_box<'a>(
            b: &'a BoxFragment,
            origin: Point,
            visit: &mut impl FnMut(FragmentRef<'a>, Point),
        ) {
            visit(FragmentRef::Box(b), origin);
            let own_origin = origin + b.border_rect.origin();
            for child in b.children.iter() {
                match child {
                    Fragment::Box(cb) => walk_box(cb, own_origin, visit),
                    Fragment::Text(t) => visit(FragmentRef::Text(t), own_origin),
                }
            }
        }
        if let Some(root) = &self.root {
            walk_box(root, Point::default(), &mut visit);
        }
    }

    /// The union of the absolute border boxes of each element's fragments
    /// (pseudo-element boxes excluded).
    pub fn element_boxes(&self) -> std::collections::HashMap<NodeId, Rect> {
        let mut boxes: std::collections::HashMap<NodeId, Rect> = std::collections::HashMap::new();
        self.walk(|f, origin| {
            if let FragmentRef::Box(b) = f
                && let Some(node) = b.node
                && b.pseudo.is_none()
            {
                let rect = b.border_rect.translate(origin);
                boxes
                    .entry(node)
                    .and_modify(|r| *r = r.union(&rect))
                    .or_insert(rect);
            }
        });
        boxes
    }

    /// The absolute border boxes of all fragments generated by `node`, in
    /// tree order. An inline element split across lines has several.
    pub fn border_boxes(&self, node: NodeId) -> Vec<Rect> {
        let mut out = Vec::new();
        self.walk(|f, origin| {
            if let FragmentRef::Box(b) = f
                && b.node == Some(node)
                && b.pseudo.is_none()
            {
                out.push(b.border_rect.translate(origin));
            }
        });
        out
    }
}

/// A fragment.
#[derive(Clone, Debug)]
pub enum Fragment {
    /// A box (block, inline box piece, atomic inline, replaced element).
    Box(BoxFragment),
    /// A run of glyphs on one line.
    Text(TextFragment),
}

impl Fragment {
    /// Moves the fragment by (`dx`, `dy`) relative to its parent.
    pub(crate) fn move_by(&mut self, dx: f32, dy: f32) {
        let rect = match self {
            Fragment::Box(b) => &mut b.border_rect,
            Fragment::Text(t) => &mut t.rect,
        };
        rect.x += dx;
        rect.y += dy;
    }
}

/// What a box fragment contains besides its children.
#[derive(Clone, Debug, PartialEq)]
pub enum BoxContent {
    /// Nothing special.
    None,
    /// The image of a replaced element, painted into the content box.
    Image(NodeId),
    /// A table. Its border box contains its captions; the table's
    /// background and border are painted around the grid.
    Table(Arc<TablePaint>),
    /// A table cell that paints more than its own background and border.
    TableCell(Arc<CellPaint>),
    /// A table row group or row. It paints no background or border (cells
    /// paint them, see [`CellPaint`]).
    TablePart,
    /// A box that only has geometry: it paints nothing and hit testing
    /// does not find it. Table column groups and columns (their boxes cover
    /// their cells), and the part of an inline box around a block-level
    /// child.
    GeometryOnly,
}

/// What a table paints besides its children.
#[derive(Clone, Debug, PartialEq)]
pub struct TablePaint {
    /// The table grid box (the area without captions), relative to the
    /// table's border box. The table's background and border fill it.
    pub grid: Rect,
    /// The borders of the collapsing border model, painted by the table
    /// after its cells; `None` in the separated border model (the table
    /// paints its own border).
    pub collapsed: Option<Vec<CollapsedEdge>>,
}

/// A segment of a collapsed border, relative to the table's border box.
#[derive(Clone, Debug, PartialEq)]
pub struct CollapsedEdge {
    /// The area of the segment.
    pub rect: Rect,
    /// True for a vertical segment (between columns).
    pub vertical: bool,
    /// The border style.
    pub style: swb_style::BorderStyle,
    /// The border color.
    pub color: swb_style::Rgba,
}

/// What a table cell paints besides its own background and border.
#[derive(Clone, Debug, PartialEq)]
pub struct CellPaint {
    /// The backgrounds of its column group, column, row group and row, in
    /// paint order (CSS 2.2 §17.5.1), painted below its own background.
    pub backgrounds: Vec<PartBackground>,
    /// True if the cell paints no background and border
    /// (`empty-cells: hide` and no content).
    pub hidden: bool,
    /// True if the table paints the cell's borders (collapsing borders).
    pub collapsed_borders: bool,
}

/// The background of a table part, painted in a cell.
#[derive(Clone, Debug, PartialEq)]
pub struct PartBackground {
    /// The style with the background.
    pub style: Arc<ComputedStyle>,
    /// The part's border box (the background positioning area), relative
    /// to the cell's border box.
    pub area: Rect,
    /// The area to paint, relative to the cell's border box.
    pub clip: Rect,
}

/// The fragment of a box.
#[derive(Clone, Debug)]
pub struct BoxFragment {
    /// The element that generated the box; `None` for anonymous boxes.
    pub node: Option<NodeId>,
    /// The pseudo-element, if the box was generated by one.
    pub pseudo: Option<PseudoKind>,
    /// The box's computed style.
    pub style: Arc<ComputedStyle>,
    /// The border box, relative to the parent fragment's border-box origin.
    pub border_rect: Rect,
    /// Border widths. For inline boxes split across lines, the sides at the
    /// split are zero.
    pub border: Edges,
    /// Padding widths (split sides zero, as for `border`).
    pub padding: Edges,
    /// Replaced content.
    pub content: BoxContent,
    /// Child fragments. Shared, so that copying a fragment is cheap: the
    /// flex item cache returns copies of laid-out subtrees.
    pub children: Arc<Vec<Fragment>>,
    /// The baseline of the first line box in the box (or of the first flex
    /// item that has one), relative to the border-box top, if any.
    pub first_baseline: Option<f32>,
    /// The baseline of the last line box in the box, relative to the
    /// border-box top, if any. The baseline of an inline-block. For a flex
    /// container, the same as `first_baseline`.
    pub last_baseline: Option<f32>,
    /// True if this fragment is part of an inline box (not a block).
    pub is_inline: bool,
}

impl BoxFragment {
    /// The padding box, relative to the parent's border-box origin.
    pub fn padding_rect(&self) -> Rect {
        self.border_rect.inset(&self.border)
    }

    /// The content box, relative to the parent's border-box origin.
    pub fn content_rect(&self) -> Rect {
        self.padding_rect().inset(&self.padding)
    }
}

/// A positioned glyph.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct PositionedGlyph {
    /// The glyph.
    pub id: GlyphId,
    /// Horizontal pen position relative to the text fragment's left edge.
    pub x: f32,
    /// Vertical offset from the baseline (down is positive).
    pub y: f32,
}

/// A caret stop in a text fragment: a boundary between glyph clusters.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Caret {
    /// Byte offset in the data of the text node. Always a character
    /// boundary.
    pub offset: u32,
    /// Horizontal position relative to the fragment's left edge.
    pub x: f32,
}

/// A run of glyphs in one font on one line.
#[derive(Clone, Debug)]
pub struct TextFragment {
    /// The text node.
    pub node: NodeId,
    /// The style of the text (the parent element's style).
    pub style: Arc<ComputedStyle>,
    /// The text's content area (font ascent to descent), relative to the
    /// parent fragment's border-box origin.
    pub rect: Rect,
    /// The baseline position, relative to `rect.y`.
    pub baseline: f32,
    /// The font.
    pub font: FontId,
    /// The font size in px.
    pub font_size: f32,
    /// The glyphs.
    pub glyphs: Arc<[PositionedGlyph]>,
    /// The text of the run (after white-space processing). For debugging
    /// dumps.
    pub text: Arc<str>,
    /// The caret stops in visual order, from the left edge to the right
    /// edge of the glyphs. Empty for generated content (pseudo-elements,
    /// list markers), which cannot be selected.
    pub carets: Arc<[Caret]>,
    /// The top of the line box that contains the fragment, relative to
    /// `rect.y` (the selection highlight fills the line box).
    pub line_top: f32,
    /// The height of the line box.
    pub line_height: f32,
}

impl TextFragment {
    /// True if the text comes from a text node and can be selected
    /// (`user-select` is not `none`).
    pub fn is_selectable(&self) -> bool {
        !self.carets.is_empty() && self.style.user_select != swb_style::UserSelect::None
    }

    /// The range of node offsets that the fragment shows.
    pub fn node_range(&self) -> Option<(u32, u32)> {
        Some((self.carets.first()?.offset, self.carets.last()?.offset))
    }

    /// The node offset of the caret stop nearest to `x` (relative to the
    /// fragment's left edge). The caret stops are searched one by one:
    /// their x positions decrease with a large negative `letter-spacing`.
    pub fn offset_at(&self, x: f32) -> Option<u32> {
        self.carets
            .iter()
            .min_by(|a, b| (a.x - x).abs().total_cmp(&(b.x - x).abs()))
            .map(|c| c.offset)
    }

    /// The node offset of the start of the cluster at `x` (relative to the
    /// fragment's left edge): the rightmost cluster start at or before `x`,
    /// or the leftmost one if `x` is before all of them.
    pub fn cluster_at(&self, x: f32) -> Option<u32> {
        // The end stop starts no cluster.
        let starts = self.carets.get(..self.carets.len().checked_sub(1)?)?;
        starts
            .iter()
            .filter(|c| c.x <= x)
            .max_by(|a, b| a.x.total_cmp(&b.x))
            .or_else(|| starts.iter().min_by(|a, b| a.x.total_cmp(&b.x)))
            .map(|c| c.offset)
    }

    /// The horizontal extent (relative to the fragment's left edge) of the
    /// node offsets `start..end`, if it is not empty.
    pub fn x_range(&self, start: u32, end: u32) -> Option<(f32, f32)> {
        let left = self.carets.iter().find(|c| c.offset >= start)?;
        let right = self.carets.iter().rev().find(|c| c.offset <= end)?;
        (right.x > left.x).then_some((left.x, right.x))
    }
}
