[package]
name = "swb-dom"
description = "Arena-based DOM tree and HTML parsing."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
encoding_rs.workspace = true
html5ever.workspace = true
log.workspace = true
markup5ever.workspace = true
