[package]
name = "swb-style"
description = "CSS properties, cascade, inheritance and computed values."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
bitflags.workspace = true
log.workspace = true
smallvec.workspace = true
svgtypes.workspace = true
swb-css.workspace = true
swb-dom.workspace = true
url.workspace = true
