[package]
name = "swb-js-regexp"
description = "JavaScript regular expressions: pattern parser, compiler and matcher."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
swb-js-text.workspace = true
thiserror.workspace = true
